query GetHomeData {
  homeData {
    sliderData {
      actionURL
      imageURL
      color
    }

    featuredProducts {
      id
      title
      slug
      tag
      currentPrice
      basePrice
      preview
    }
  }
}
