// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Lang struct {
	Name string `json:"name"`
	Ext  string `json:"ext"`
}

type User struct {
	ID       string  `json:"id"`
	Nickname string  `json:"nickname"`
	Email    string  `json:"email"`
	Role     int     `json:"role"`
	Langs    []*Lang `json:"langs"`
}
