import Head from 'next/head'
import Modal from 'react-modal'
import client from '../apollo/apollo'
import type { AppProps } from 'next/app'
import RootLayout from '@/components/RootLayout'
import { useTheme } from '@/hooks'
import { ApolloProvider } from '@apollo/client'
import { ThemeProvider } from '@/providers/theme'
import SwiperCore from 'swiper'
import { Autoplay, EffectFade, Navigation, Pagination, Thumbs } from 'swiper/modules'

import { appWithTranslation } from 'next-i18next'
import nextI18NextConfig from '../../next-i18next.config'

import '../../node_modules/modern-normalize/modern-normalize.css'
import '@/styles/global.scss'
import 'swiper/css'
import 'swiper/css/navigation'
import 'swiper/css/effect-fade'
import 'swiper/css/pagination'

type AppPropsWithLayout = AppProps

Modal.setAppElement('#__next')

SwiperCore.use([Navigation, Pagination, Autoplay, EffectFade, Thumbs])

const MyApp = ({ Component, pageProps }: AppPropsWithLayout) => {
  const [theme, changeTheme] = useTheme()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
      </Head>
      <ApolloProvider client={client}>
        <ThemeProvider>
          <RootLayout theme={theme} onThemeChange={changeTheme}>
            <Component {...pageProps} />
          </RootLayout>
        </ThemeProvider>
      </ApolloProvider>
    </>
  )
}

// INFO: https://github.com/i18next/next-i18next/issues/1917
export default appWithTranslation(MyApp, nextI18NextConfig)
