import Head from 'next/head'
import type { AppProps } from 'next/app'
import RootLayout from '@/components/RootLayout'
import { ApolloProvider } from '@apollo/client'
import { ThemeProvider } from 'styled-components'
import { GlobalStyles, lightTheme } from '@/utils/theme'
import client from '../apollo/apollo'

import { appWithTranslation } from 'next-i18next'

import '../../node_modules/modern-normalize/modern-normalize.css'
import '@/styles/css-variables.scss'
type AppPropsWithLayout = AppProps

// import { Montserrat } from 'next/font/google'
// const montserrat = Montserrat({
//   weight: ['400', '500', '600'],
//   display: 'swap'
// })

const MyApp = ({ Component, pageProps }: AppPropsWithLayout) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
      </Head>
      <ApolloProvider client={client}>
        <ThemeProvider theme={lightTheme}>
          <GlobalStyles />
          <RootLayout>
            <Component {...pageProps} />
          </RootLayout>
        </ThemeProvider>
      </ApolloProvider>
    </>
  )
}

export default appWithTranslation(MyApp)
