query allProducts($gender: [Gender], $instock: Boolean) {
  products(filter: { gender: $gender, instock: $instock }) {
    id
    title
    instock
    price
    discount
    mainTag
    preview
  }
}
