query GetProduct($id: ID!) {
  product(id: $id) {
    __typename
    ... on Product {
      id
      title
      instock
      currentPrice
      basePrice
      preview
      gender
      category
      details {
        description
        color
        images
        delivery
        dimensions
      }
    }
    ... on NotFound {
      message
    }
  }
}
