query AllProducts(
  $gender: [Gender]
  $isHidden: Boolean = false
  $instock: Boolean
  $mainTag: MainTag
  $price: PriceRange
  $category: [CategoryType]
  $page: Int!
) {
  allProducts(
    filter: {
      gender: $gender
      isHidden: $isHidden
      instock: $instock
      mainTag: $mainTag
      price: $price
      category: $category
      page: $page
    }
  ) {
    priceRange {
      gt
      lt
    }
    pagination {
      totalPages
      currentPage
    }
    products {
      id
      slug
      title
      instock
      currentPrice
      basePrice
      mainTag
      preview
    }
  }
}
