query AllProducts(
  $gender: [Gender]
  $isHidden: Boolean = false
  $instock: Boolean
  $mainTag: MainTag
  $price: PriceRange
  $category: [CategoryType]
) {
  allProducts(
    filter: {
      gender: $gender
      isHidden: $isHidden
      instock: $instock
      mainTag: $mainTag
      price: $price
      category: $category
    }
  ) {
    priceRange {
      lt
      gt
    }
    products {
      id
      title
      instock
      currentPrice
      basePrice
      mainTag
      preview
    }
  }
}
