query getProductByID($id: ID!) {
  product(id: $id) {
    __typename
    ... on Product {
      id
      title
      currentPrice
      basePrice
      tags
      images
      description
      instock
      features {
        material
        color
        gender
        category
      }
    }
    ... on NotFound {
      message
    }
  }
}
